### ISSUE TITLE
Bug: Gnomock is not working with a remote docker host

### ISSUE THREAD

**Issue by Kwutzke** [orlangure/gnomock#106]
**Describe the bug**
When starting the docker containers on a remote host (e.g. by setting DOCKER_HOST env var), the containers are starting just fine, but the host field of the container object is still set to localhost which leads to failing healthcheck

**To Reproduce**
- Set DOCKER_HOST to a valid remote host 
- Run tests

**Expected behavior**
The container field host should be set to the remote host from DOCKER_HOST env variable. 
An alternative for setting the DOCKER_HOST env variable could be adding the option to set a remote host. 

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. MacOS] MacOS
 - Version [e.g. 0.9.2] 0.12.1
 - Docker version 20.10.5

**Additional context**

**Comment by orlangure** [comment]
Hi @Kwutzke, thanks for the report!

You are right, external docker host wasn't supported, and [the docs](https://github.com/orlangure/gnomock#getting-started) mention that local docker daemon is required:
> Both ways require an active Docker daemon running locally in the same environment.

However, I tried to implement it in #107 so it would be possible to use Gnomock with remote docker hosts. For now this feature will be considered experimental, because I can't think of a good way to test it properly during CI. From my manual tests it seems to work.

I'll merge and release it in a day or two. For now, could you try running your tests using `support-external-docker-host` branch?

```
go get github.com/orlangure/gnomock@support-external-docker-host
```
